// Code generated by entc, DO NOT EDIT.

package alias

import (
	"time"
)

const (
	// Label holds the string label denoting the alias type in the database.
	Label = "alias"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldPv holds the string denoting the pv field in the database.
	FieldPv = "pv"
	// FieldExpire holds the string denoting the expire field in the database.
	FieldExpire = "expire"
	// Table holds the table name of the alias in the database.
	Table = "alias"
)

// Columns holds all SQL columns for alias fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldKey,
	FieldURL,
	FieldPv,
	FieldExpire,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultKey holds the default value on creation for the "key" field.
	DefaultKey string
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// DefaultURL holds the default value on creation for the "url" field.
	DefaultURL string
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// DefaultPv holds the default value on creation for the "pv" field.
	DefaultPv uint64
)
