// Code generated by entc, DO NOT EDIT.

package shorturl

import (
	"time"
)

const (
	// Label holds the string label denoting the shorturl type in the database.
	Label = "short_url"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldPv holds the string denoting the pv field in the database.
	FieldPv = "pv"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldUpdateAt holds the string denoting the update_at field in the database.
	FieldUpdateAt = "update_at"

	// Table holds the table name of the shorturl in the database.
	Table = "short_urls"
)

// Columns holds all SQL columns for shorturl fields.
var Columns = []string{
	FieldID,
	FieldKey,
	FieldURL,
	FieldPv,
	FieldCreateAt,
	FieldUpdateAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultKey holds the default value on creation for the "key" field.
	DefaultKey string
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// DefaultURL holds the default value on creation for the "url" field.
	DefaultURL string
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// DefaultPv holds the default value on creation for the "pv" field.
	DefaultPv uint64
	// DefaultCreateAt holds the default value on creation for the "create_at" field.
	DefaultCreateAt func() time.Time
	// DefaultUpdateAt holds the default value on creation for the "update_at" field.
	DefaultUpdateAt func() time.Time
)
