// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/drrrMikado/shorten/internal/repo/ent/alias"
	"github.com/drrrMikado/shorten/internal/repo/ent/predicate"
)

// AliasUpdate is the builder for updating Alias entities.
type AliasUpdate struct {
	config
	hooks    []Hook
	mutation *AliasMutation
}

// Where adds a new predicate for the AliasUpdate builder.
func (au *AliasUpdate) Where(ps ...predicate.Alias) *AliasUpdate {
	au.mutation.predicates = append(au.mutation.predicates, ps...)
	return au
}

// SetKey sets the "key" field.
func (au *AliasUpdate) SetKey(s string) *AliasUpdate {
	au.mutation.SetKey(s)
	return au
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (au *AliasUpdate) SetNillableKey(s *string) *AliasUpdate {
	if s != nil {
		au.SetKey(*s)
	}
	return au
}

// SetURL sets the "url" field.
func (au *AliasUpdate) SetURL(s string) *AliasUpdate {
	au.mutation.SetURL(s)
	return au
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (au *AliasUpdate) SetNillableURL(s *string) *AliasUpdate {
	if s != nil {
		au.SetURL(*s)
	}
	return au
}

// SetPv sets the "pv" field.
func (au *AliasUpdate) SetPv(u uint64) *AliasUpdate {
	au.mutation.ResetPv()
	au.mutation.SetPv(u)
	return au
}

// SetNillablePv sets the "pv" field if the given value is not nil.
func (au *AliasUpdate) SetNillablePv(u *uint64) *AliasUpdate {
	if u != nil {
		au.SetPv(*u)
	}
	return au
}

// AddPv adds u to the "pv" field.
func (au *AliasUpdate) AddPv(u uint64) *AliasUpdate {
	au.mutation.AddPv(u)
	return au
}

// ClearPv clears the value of the "pv" field.
func (au *AliasUpdate) ClearPv() *AliasUpdate {
	au.mutation.ClearPv()
	return au
}

// SetExpire sets the "expire" field.
func (au *AliasUpdate) SetExpire(t time.Time) *AliasUpdate {
	au.mutation.SetExpire(t)
	return au
}

// SetNillableExpire sets the "expire" field if the given value is not nil.
func (au *AliasUpdate) SetNillableExpire(t *time.Time) *AliasUpdate {
	if t != nil {
		au.SetExpire(*t)
	}
	return au
}

// ClearExpire clears the value of the "expire" field.
func (au *AliasUpdate) ClearExpire() *AliasUpdate {
	au.mutation.ClearExpire()
	return au
}

// Mutation returns the AliasMutation object of the builder.
func (au *AliasUpdate) Mutation() *AliasMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AliasUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	au.defaults()
	if len(au.hooks) == 0 {
		if err = au.check(); err != nil {
			return 0, err
		}
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AliasMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = au.check(); err != nil {
				return 0, err
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *AliasUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AliasUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AliasUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *AliasUpdate) defaults() {
	if _, ok := au.mutation.UpdateTime(); !ok {
		v := alias.UpdateDefaultUpdateTime()
		au.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AliasUpdate) check() error {
	if v, ok := au.mutation.Key(); ok {
		if err := alias.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf("ent: validator failed for field \"key\": %w", err)}
		}
	}
	if v, ok := au.mutation.URL(); ok {
		if err := alias.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf("ent: validator failed for field \"url\": %w", err)}
		}
	}
	return nil
}

func (au *AliasUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   alias.Table,
			Columns: alias.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: alias.FieldID,
			},
		},
	}
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: alias.FieldUpdateTime,
		})
	}
	if value, ok := au.mutation.Key(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: alias.FieldKey,
		})
	}
	if value, ok := au.mutation.URL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: alias.FieldURL,
		})
	}
	if value, ok := au.mutation.Pv(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: alias.FieldPv,
		})
	}
	if value, ok := au.mutation.AddedPv(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: alias.FieldPv,
		})
	}
	if au.mutation.PvCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Column: alias.FieldPv,
		})
	}
	if value, ok := au.mutation.Expire(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: alias.FieldExpire,
		})
	}
	if au.mutation.ExpireCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: alias.FieldExpire,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alias.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// AliasUpdateOne is the builder for updating a single Alias entity.
type AliasUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AliasMutation
}

// SetKey sets the "key" field.
func (auo *AliasUpdateOne) SetKey(s string) *AliasUpdateOne {
	auo.mutation.SetKey(s)
	return auo
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (auo *AliasUpdateOne) SetNillableKey(s *string) *AliasUpdateOne {
	if s != nil {
		auo.SetKey(*s)
	}
	return auo
}

// SetURL sets the "url" field.
func (auo *AliasUpdateOne) SetURL(s string) *AliasUpdateOne {
	auo.mutation.SetURL(s)
	return auo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (auo *AliasUpdateOne) SetNillableURL(s *string) *AliasUpdateOne {
	if s != nil {
		auo.SetURL(*s)
	}
	return auo
}

// SetPv sets the "pv" field.
func (auo *AliasUpdateOne) SetPv(u uint64) *AliasUpdateOne {
	auo.mutation.ResetPv()
	auo.mutation.SetPv(u)
	return auo
}

// SetNillablePv sets the "pv" field if the given value is not nil.
func (auo *AliasUpdateOne) SetNillablePv(u *uint64) *AliasUpdateOne {
	if u != nil {
		auo.SetPv(*u)
	}
	return auo
}

// AddPv adds u to the "pv" field.
func (auo *AliasUpdateOne) AddPv(u uint64) *AliasUpdateOne {
	auo.mutation.AddPv(u)
	return auo
}

// ClearPv clears the value of the "pv" field.
func (auo *AliasUpdateOne) ClearPv() *AliasUpdateOne {
	auo.mutation.ClearPv()
	return auo
}

// SetExpire sets the "expire" field.
func (auo *AliasUpdateOne) SetExpire(t time.Time) *AliasUpdateOne {
	auo.mutation.SetExpire(t)
	return auo
}

// SetNillableExpire sets the "expire" field if the given value is not nil.
func (auo *AliasUpdateOne) SetNillableExpire(t *time.Time) *AliasUpdateOne {
	if t != nil {
		auo.SetExpire(*t)
	}
	return auo
}

// ClearExpire clears the value of the "expire" field.
func (auo *AliasUpdateOne) ClearExpire() *AliasUpdateOne {
	auo.mutation.ClearExpire()
	return auo
}

// Mutation returns the AliasMutation object of the builder.
func (auo *AliasUpdateOne) Mutation() *AliasMutation {
	return auo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AliasUpdateOne) Select(field string, fields ...string) *AliasUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Alias entity.
func (auo *AliasUpdateOne) Save(ctx context.Context) (*Alias, error) {
	var (
		err  error
		node *Alias
	)
	auo.defaults()
	if len(auo.hooks) == 0 {
		if err = auo.check(); err != nil {
			return nil, err
		}
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AliasMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = auo.check(); err != nil {
				return nil, err
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			mut = auo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, auo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AliasUpdateOne) SaveX(ctx context.Context) *Alias {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AliasUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AliasUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *AliasUpdateOne) defaults() {
	if _, ok := auo.mutation.UpdateTime(); !ok {
		v := alias.UpdateDefaultUpdateTime()
		auo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AliasUpdateOne) check() error {
	if v, ok := auo.mutation.Key(); ok {
		if err := alias.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf("ent: validator failed for field \"key\": %w", err)}
		}
	}
	if v, ok := auo.mutation.URL(); ok {
		if err := alias.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf("ent: validator failed for field \"url\": %w", err)}
		}
	}
	return nil
}

func (auo *AliasUpdateOne) sqlSave(ctx context.Context) (_node *Alias, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   alias.Table,
			Columns: alias.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: alias.FieldID,
			},
		},
	}
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Alias.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alias.FieldID)
		for _, f := range fields {
			if !alias.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != alias.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: alias.FieldUpdateTime,
		})
	}
	if value, ok := auo.mutation.Key(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: alias.FieldKey,
		})
	}
	if value, ok := auo.mutation.URL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: alias.FieldURL,
		})
	}
	if value, ok := auo.mutation.Pv(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: alias.FieldPv,
		})
	}
	if value, ok := auo.mutation.AddedPv(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: alias.FieldPv,
		})
	}
	if auo.mutation.PvCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Column: alias.FieldPv,
		})
	}
	if value, ok := auo.mutation.Expire(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: alias.FieldExpire,
		})
	}
	if auo.mutation.ExpireCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: alias.FieldExpire,
		})
	}
	_node = &Alias{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alias.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
