// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/drrrMikado/shorten/internal/repo/ent/migrate"

	"github.com/drrrMikado/shorten/internal/repo/ent/alias"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Alias is the client for interacting with the Alias builders.
	Alias *AliasClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Alias = NewAliasClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Alias:  NewAliasClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config: cfg,
		Alias:  NewAliasClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Alias.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Alias.Use(hooks...)
}

// AliasClient is a client for the Alias schema.
type AliasClient struct {
	config
}

// NewAliasClient returns a client for the Alias from the given config.
func NewAliasClient(c config) *AliasClient {
	return &AliasClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `alias.Hooks(f(g(h())))`.
func (c *AliasClient) Use(hooks ...Hook) {
	c.hooks.Alias = append(c.hooks.Alias, hooks...)
}

// Create returns a create builder for Alias.
func (c *AliasClient) Create() *AliasCreate {
	mutation := newAliasMutation(c.config, OpCreate)
	return &AliasCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Alias entities.
func (c *AliasClient) CreateBulk(builders ...*AliasCreate) *AliasCreateBulk {
	return &AliasCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Alias.
func (c *AliasClient) Update() *AliasUpdate {
	mutation := newAliasMutation(c.config, OpUpdate)
	return &AliasUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AliasClient) UpdateOne(a *Alias) *AliasUpdateOne {
	mutation := newAliasMutation(c.config, OpUpdateOne, withAlias(a))
	return &AliasUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AliasClient) UpdateOneID(id int) *AliasUpdateOne {
	mutation := newAliasMutation(c.config, OpUpdateOne, withAliasID(id))
	return &AliasUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Alias.
func (c *AliasClient) Delete() *AliasDelete {
	mutation := newAliasMutation(c.config, OpDelete)
	return &AliasDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *AliasClient) DeleteOne(a *Alias) *AliasDeleteOne {
	return c.DeleteOneID(a.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *AliasClient) DeleteOneID(id int) *AliasDeleteOne {
	builder := c.Delete().Where(alias.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AliasDeleteOne{builder}
}

// Query returns a query builder for Alias.
func (c *AliasClient) Query() *AliasQuery {
	return &AliasQuery{
		config: c.config,
	}
}

// Get returns a Alias entity by its id.
func (c *AliasClient) Get(ctx context.Context, id int) (*Alias, error) {
	return c.Query().Where(alias.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AliasClient) GetX(ctx context.Context, id int) *Alias {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AliasClient) Hooks() []Hook {
	return c.hooks.Alias
}
