// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/drrrMikado/shorten/internal/repo/ent/predicate"
	"github.com/drrrMikado/shorten/internal/repo/ent/shorturl"
)

// ShortUrlDelete is the builder for deleting a ShortUrl entity.
type ShortUrlDelete struct {
	config
	hooks    []Hook
	mutation *ShortUrlMutation
}

// Where adds a new predicate to the ShortUrlDelete builder.
func (sud *ShortUrlDelete) Where(ps ...predicate.ShortUrl) *ShortUrlDelete {
	sud.mutation.predicates = append(sud.mutation.predicates, ps...)
	return sud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sud *ShortUrlDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sud.hooks) == 0 {
		affected, err = sud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ShortUrlMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sud.mutation = mutation
			affected, err = sud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sud.hooks) - 1; i >= 0; i-- {
			mut = sud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sud *ShortUrlDelete) ExecX(ctx context.Context) int {
	n, err := sud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sud *ShortUrlDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: shorturl.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: shorturl.FieldID,
			},
		},
	}
	if ps := sud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, sud.driver, _spec)
}

// ShortUrlDeleteOne is the builder for deleting a single ShortUrl entity.
type ShortUrlDeleteOne struct {
	sud *ShortUrlDelete
}

// Exec executes the deletion query.
func (sudo *ShortUrlDeleteOne) Exec(ctx context.Context) error {
	n, err := sudo.sud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shorturl.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sudo *ShortUrlDeleteOne) ExecX(ctx context.Context) {
	sudo.sud.ExecX(ctx)
}
