// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/drrrMikado/shorten/ent/migrate"

	"github.com/drrrMikado/shorten/ent/shorturl"

	"github.com/facebook/ent/dialect"
	"github.com/facebook/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ShortUrl is the client for interacting with the ShortUrl builders.
	ShortUrl *ShortUrlClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ShortUrl = NewShortUrlClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		ShortUrl: NewShortUrlClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(*sql.Driver).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: &txDriver{tx: tx, drv: c.driver}, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		config:   cfg,
		ShortUrl: NewShortUrlClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ShortUrl.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.ShortUrl.Use(hooks...)
}

// ShortUrlClient is a client for the ShortUrl schema.
type ShortUrlClient struct {
	config
}

// NewShortUrlClient returns a client for the ShortUrl from the given config.
func NewShortUrlClient(c config) *ShortUrlClient {
	return &ShortUrlClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `shorturl.Hooks(f(g(h())))`.
func (c *ShortUrlClient) Use(hooks ...Hook) {
	c.hooks.ShortUrl = append(c.hooks.ShortUrl, hooks...)
}

// Create returns a create builder for ShortUrl.
func (c *ShortUrlClient) Create() *ShortUrlCreate {
	mutation := newShortUrlMutation(c.config, OpCreate)
	return &ShortUrlCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ShortUrl entities.
func (c *ShortUrlClient) CreateBulk(builders ...*ShortUrlCreate) *ShortUrlCreateBulk {
	return &ShortUrlCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ShortUrl.
func (c *ShortUrlClient) Update() *ShortUrlUpdate {
	mutation := newShortUrlMutation(c.config, OpUpdate)
	return &ShortUrlUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ShortUrlClient) UpdateOne(su *ShortUrl) *ShortUrlUpdateOne {
	mutation := newShortUrlMutation(c.config, OpUpdateOne, withShortUrl(su))
	return &ShortUrlUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ShortUrlClient) UpdateOneID(id int) *ShortUrlUpdateOne {
	mutation := newShortUrlMutation(c.config, OpUpdateOne, withShortUrlID(id))
	return &ShortUrlUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ShortUrl.
func (c *ShortUrlClient) Delete() *ShortUrlDelete {
	mutation := newShortUrlMutation(c.config, OpDelete)
	return &ShortUrlDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ShortUrlClient) DeleteOne(su *ShortUrl) *ShortUrlDeleteOne {
	return c.DeleteOneID(su.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ShortUrlClient) DeleteOneID(id int) *ShortUrlDeleteOne {
	builder := c.Delete().Where(shorturl.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ShortUrlDeleteOne{builder}
}

// Query returns a query builder for ShortUrl.
func (c *ShortUrlClient) Query() *ShortUrlQuery {
	return &ShortUrlQuery{config: c.config}
}

// Get returns a ShortUrl entity by its id.
func (c *ShortUrlClient) Get(ctx context.Context, id int) (*ShortUrl, error) {
	return c.Query().Where(shorturl.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ShortUrlClient) GetX(ctx context.Context, id int) *ShortUrl {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ShortUrlClient) Hooks() []Hook {
	return c.hooks.ShortUrl
}
