// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/drrrMikado/shorten/ent/predicate"
	"github.com/drrrMikado/shorten/ent/shorturl"

	"github.com/facebook/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeShortUrl = "ShortUrl"
)

// ShortUrlMutation represents an operation that mutates the ShortUrl nodes in the graph.
type ShortUrlMutation struct {
	config
	op            Op
	typ           string
	id            *int
	key           *string
	short_url     *string
	long_url      *string
	create_at     *time.Time
	update_at     *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*ShortUrl, error)
	predicates    []predicate.ShortUrl
}

var _ ent.Mutation = (*ShortUrlMutation)(nil)

// shorturlOption allows management of the mutation configuration using functional options.
type shorturlOption func(*ShortUrlMutation)

// newShortUrlMutation creates new mutation for the ShortUrl entity.
func newShortUrlMutation(c config, op Op, opts ...shorturlOption) *ShortUrlMutation {
	m := &ShortUrlMutation{
		config:        c,
		op:            op,
		typ:           TypeShortUrl,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withShortUrlID sets the ID field of the mutation.
func withShortUrlID(id int) shorturlOption {
	return func(m *ShortUrlMutation) {
		var (
			err   error
			once  sync.Once
			value *ShortUrl
		)
		m.oldValue = func(ctx context.Context) (*ShortUrl, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ShortUrl.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withShortUrl sets the old ShortUrl of the mutation.
func withShortUrl(node *ShortUrl) shorturlOption {
	return func(m *ShortUrlMutation) {
		m.oldValue = func(context.Context) (*ShortUrl, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ShortUrlMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ShortUrlMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID
// is only available if it was provided to the builder.
func (m *ShortUrlMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetKey sets the "key" field.
func (m *ShortUrlMutation) SetKey(s string) {
	m.key = &s
}

// Key returns the value of the "key" field in the mutation.
func (m *ShortUrlMutation) Key() (r string, exists bool) {
	v := m.key
	if v == nil {
		return
	}
	return *v, true
}

// OldKey returns the old "key" field's value of the ShortUrl entity.
// If the ShortUrl object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShortUrlMutation) OldKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKey: %w", err)
	}
	return oldValue.Key, nil
}

// ResetKey resets all changes to the "key" field.
func (m *ShortUrlMutation) ResetKey() {
	m.key = nil
}

// SetShortURL sets the "short_url" field.
func (m *ShortUrlMutation) SetShortURL(s string) {
	m.short_url = &s
}

// ShortURL returns the value of the "short_url" field in the mutation.
func (m *ShortUrlMutation) ShortURL() (r string, exists bool) {
	v := m.short_url
	if v == nil {
		return
	}
	return *v, true
}

// OldShortURL returns the old "short_url" field's value of the ShortUrl entity.
// If the ShortUrl object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShortUrlMutation) OldShortURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldShortURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldShortURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldShortURL: %w", err)
	}
	return oldValue.ShortURL, nil
}

// ResetShortURL resets all changes to the "short_url" field.
func (m *ShortUrlMutation) ResetShortURL() {
	m.short_url = nil
}

// SetLongURL sets the "long_url" field.
func (m *ShortUrlMutation) SetLongURL(s string) {
	m.long_url = &s
}

// LongURL returns the value of the "long_url" field in the mutation.
func (m *ShortUrlMutation) LongURL() (r string, exists bool) {
	v := m.long_url
	if v == nil {
		return
	}
	return *v, true
}

// OldLongURL returns the old "long_url" field's value of the ShortUrl entity.
// If the ShortUrl object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShortUrlMutation) OldLongURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldLongURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldLongURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLongURL: %w", err)
	}
	return oldValue.LongURL, nil
}

// ResetLongURL resets all changes to the "long_url" field.
func (m *ShortUrlMutation) ResetLongURL() {
	m.long_url = nil
}

// SetCreateAt sets the "create_at" field.
func (m *ShortUrlMutation) SetCreateAt(t time.Time) {
	m.create_at = &t
}

// CreateAt returns the value of the "create_at" field in the mutation.
func (m *ShortUrlMutation) CreateAt() (r time.Time, exists bool) {
	v := m.create_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateAt returns the old "create_at" field's value of the ShortUrl entity.
// If the ShortUrl object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShortUrlMutation) OldCreateAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldCreateAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldCreateAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateAt: %w", err)
	}
	return oldValue.CreateAt, nil
}

// ResetCreateAt resets all changes to the "create_at" field.
func (m *ShortUrlMutation) ResetCreateAt() {
	m.create_at = nil
}

// SetUpdateAt sets the "update_at" field.
func (m *ShortUrlMutation) SetUpdateAt(t time.Time) {
	m.update_at = &t
}

// UpdateAt returns the value of the "update_at" field in the mutation.
func (m *ShortUrlMutation) UpdateAt() (r time.Time, exists bool) {
	v := m.update_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateAt returns the old "update_at" field's value of the ShortUrl entity.
// If the ShortUrl object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ShortUrlMutation) OldUpdateAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldUpdateAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldUpdateAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateAt: %w", err)
	}
	return oldValue.UpdateAt, nil
}

// ResetUpdateAt resets all changes to the "update_at" field.
func (m *ShortUrlMutation) ResetUpdateAt() {
	m.update_at = nil
}

// Op returns the operation name.
func (m *ShortUrlMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (ShortUrl).
func (m *ShortUrlMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ShortUrlMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.key != nil {
		fields = append(fields, shorturl.FieldKey)
	}
	if m.short_url != nil {
		fields = append(fields, shorturl.FieldShortURL)
	}
	if m.long_url != nil {
		fields = append(fields, shorturl.FieldLongURL)
	}
	if m.create_at != nil {
		fields = append(fields, shorturl.FieldCreateAt)
	}
	if m.update_at != nil {
		fields = append(fields, shorturl.FieldUpdateAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ShortUrlMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case shorturl.FieldKey:
		return m.Key()
	case shorturl.FieldShortURL:
		return m.ShortURL()
	case shorturl.FieldLongURL:
		return m.LongURL()
	case shorturl.FieldCreateAt:
		return m.CreateAt()
	case shorturl.FieldUpdateAt:
		return m.UpdateAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ShortUrlMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case shorturl.FieldKey:
		return m.OldKey(ctx)
	case shorturl.FieldShortURL:
		return m.OldShortURL(ctx)
	case shorturl.FieldLongURL:
		return m.OldLongURL(ctx)
	case shorturl.FieldCreateAt:
		return m.OldCreateAt(ctx)
	case shorturl.FieldUpdateAt:
		return m.OldUpdateAt(ctx)
	}
	return nil, fmt.Errorf("unknown ShortUrl field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ShortUrlMutation) SetField(name string, value ent.Value) error {
	switch name {
	case shorturl.FieldKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKey(v)
		return nil
	case shorturl.FieldShortURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetShortURL(v)
		return nil
	case shorturl.FieldLongURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLongURL(v)
		return nil
	case shorturl.FieldCreateAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateAt(v)
		return nil
	case shorturl.FieldUpdateAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateAt(v)
		return nil
	}
	return fmt.Errorf("unknown ShortUrl field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ShortUrlMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ShortUrlMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ShortUrlMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ShortUrl numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ShortUrlMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ShortUrlMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ShortUrlMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ShortUrl nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ShortUrlMutation) ResetField(name string) error {
	switch name {
	case shorturl.FieldKey:
		m.ResetKey()
		return nil
	case shorturl.FieldShortURL:
		m.ResetShortURL()
		return nil
	case shorturl.FieldLongURL:
		m.ResetLongURL()
		return nil
	case shorturl.FieldCreateAt:
		m.ResetCreateAt()
		return nil
	case shorturl.FieldUpdateAt:
		m.ResetUpdateAt()
		return nil
	}
	return fmt.Errorf("unknown ShortUrl field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ShortUrlMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ShortUrlMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ShortUrlMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ShortUrlMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ShortUrlMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ShortUrlMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ShortUrlMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ShortUrl unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ShortUrlMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ShortUrl edge %s", name)
}
