// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/drrrMikado/shorten/internal/repo"
	"github.com/drrrMikado/shorten/internal/server"
	"github.com/drrrMikado/shorten/internal/service"
)

// Injectors from wire.go:

func InitServer(opts ...server.Option) (*server.Server, func(), error) {
	repository, cleanup, err := repo.NewRepository()
	if err != nil {
		return nil, nil, err
	}
	shorturlRepository := repository.ShortUrl
	serviceService := service.New(shorturlRepository)
	serverServer, cleanup2 := server.NewServer(serviceService, opts...)
	return serverServer, func() {
		cleanup2()
		cleanup()
	}, nil
}
