// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/drrrMikado/shorten/internal/repo"
	"github.com/drrrMikado/shorten/internal/server"
	"github.com/drrrMikado/shorten/internal/service"
	"github.com/drrrMikado/shorten/pkg/rate"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitServer(staticPath2 string, limiter *rate.Limiter) (*server.Server, func(), error) {
	repository, cleanup, err := repo.NewRepository()
	if err != nil {
		return nil, nil, err
	}
	shorturlRepository := repository.ShortUrl
	serviceService := service.New(shorturlRepository)
	serverServer, cleanup2 := server.NewServer(serviceService, staticPath2, limiter)
	return serverServer, func() {
		cleanup2()
		cleanup()
	}, nil
}
