// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// ShortUrl is the predicate function for shorturl builders.
type ShortUrl func(*sql.Selector)
